// <auto-generated />
namespace AccountManager.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class TitheTableAddition : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TitheTableAddition));
        
        string IMigrationMetadata.Id
        {
            get { return "201412261250595_TitheTableAddition"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
